name: upload-chart
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        sudo snap install helm --classic
        helm plugin install https://github.com/chartmuseum/helm-push
        helm push chart/dmarc2logstash https://charts.banzaicloud.io/gh/Codesim-LLC
